# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenCourseAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='forbiddencourseaccess',
            index=models.Index(fields=[b'username', b'course_id'], name='seb_openedx_usernam_41089f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forbiddencourseaccess',
            unique_together=set([('username', 'course_id')]),
        ),
    ]
