# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 10:32
# pylint: disable=invalid-name
""" The migration """
from __future__ import unicode_literals

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):
    """ Migration """
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenCourseAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('access_blocked', models.BooleanField(default=True)),
                ('last_modified_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_by_username', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddIndex(
            model_name='forbiddencourseaccess',
            index=models.Index(fields=['username', 'course_id'], name='seb_openedx_usernam_41089f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forbiddencourseaccess',
            unique_together=set([('username', 'course_id')]),
        ),
    ]
