# Generated by Django 3.2.19 on 2023-08-10 16:14
# pylint: disable=invalid-name
"""Migration."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """deprecation"""

    dependencies = [
        ('seb_openedx', '0002_seb_course_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sebcourseconfiguration',
            name='blacklist_chapters',
        ),
        migrations.RemoveField(
            model_name='sebcourseconfiguration',
            name='whitelist_paths',
        ),
        migrations.AlterField(
            model_name='sebcourseconfiguration',
            name='permission_components',
            field=models.TextField(blank=True, default='AlwaysAllowStaff,CheckSEBHashBrowserExamKeyOrConfigKey'),
        ),
    ]
