# Generated by Django 4.2.13 on 2024-05-08 19:44
# pylint: disable=invalid-name
"""Migration."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds the vertical/sequencial blacklist fields."""

    dependencies = [
        ('seb_openedx', '0002_seb_course_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sebcourseconfiguration',
            name='allow_mfe_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sebcourseconfiguration',
            name='blacklist_sequences',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sebcourseconfiguration',
            name='blacklist_verticals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sebcourseconfiguration',
            name='seb_enabled',
            field=models.BooleanField(default=False),
        )
    ]
