###############################################################################
#
#
###############################################################################

.DEFAULT_GOAL := help

# Generates a help message. Borrowed from https://github.com/pydanny/cookiecutter-djangopackage.
help: ## Display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@perl -nle'print $& if m{^[\.a-zA-Z_-]+:.*?## .*$$}' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}'

bumpversion: ## Tag the current version using semantinc versioning and git tags (default: minor)
	# bumpversion major
	bumpversion minor
	# bumpversion patch

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	coverage erase
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

test: clean
	pylint seb_openedx
	coverage run --source="." --rcfile=.coveragerc -m pytest seb_openedx
	coverage report --fail-under=39 --rcfile=.coveragerc

test-hawthorn: clean
	if [ "$EDX_PLATFORM_SETTINGS" = "devstack_docker" ]; then
	    ln -sfn /edx/var/edxapp/staticfiles /edx/app/edxapp/edx-platform/test_root/staticfiles
	fi
	cd /edx/src/seb-open-edx || cd ~/seb-open-edx
	pytest seb_openedx --ds seb_openedx.settings.test_hawthorn
	coverage report --fail-under=39 --rcfile=.coveragerc
