name: CI

on:
  pull_request:
    branches: ["*"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["*"]
    paths-ignore: ["docs/**"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.8", "3.11"]
        toxenv: [quality, pii_check, django32, django40]

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run coverage
        run: |
          coverage run --source="." -m pytest
          coverage report --fail-under=72 -m

      - name: Run quality analysis
        run: |
          pylint --exit-zero seb_openedx
          pycodestyle seb_openedx
