name: python36

on:
  pull_request:
    branches: [ "*" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "*" ]
    paths-ignore: [ "docs/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.6.15"
          cache: pip
          cache-dependency-path: |
            requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run coverage
        run: |
          coverage run --source="." -m pytest
          coverage report --fail-under=72 -m

      - name: Run quality analysis
        run: |
          pycodestyle seb_openedx
          pylint seb_openedx
